name: getting-started-demo

channels:
  - conda-forge
  - defaults
  - rdkit
  - openbabel
  - astropy
dependencies:
  - rdkit
  - astropy
  - aplpy
  - astroquery
  - openbabel
  - cartopy
  - imagemagick
  - graphviz
  - cython
