name: getting-started-demo

channels:
  - conda-forge
  - defaults
  - rdkit
  - openbabel
  - bjodah

dependencies:
  - rdkit
  - bokeh
  - openbabel
  - cartopy
  - imagemagick
  - graphviz
  - chempy
  - iris
  - iris-sample-data
  - metpy
  - pip
  - pip:
    - numpy
    - matplotlib
    - pandas
    - git+https://github.com/cltk/cltk.git
    - Pillow
    - LightPipes
    - rayopt
    - control
    - librosa
    - prysm
    - pybel
    - pypdb
    - pymatgen
    - py3Dmol
    - chembl_webresource_client
    - pubchempy
    - music21
    - ipyvolume
    - seaborn
    - scipy
    - k3d
    - cairosvg
    - mpld3
    - folium
    - blockdiag
    - calysto
    - sympy
    - librosa
    - git+https://github.com/innovationOUtside/ipython_magic_tikz
    - git+https://github.com/mph-/lcapy.git
    - git+https://github.com/innovationOUtside/ipython_magic_blockdiag.git
