name: getting-started-demo

channels:
  - conda-forge
  - defaults
  - rdkit
  - openbabel
  - astropy
dependencies:
  - rdkit
  - astropy
  - aplpy
  - astroquery
  - openbabel
  - cartopy
  - imagemagick
  - graphviz
  - cython
  - pip
  - pip:
    - git+https://github.com/SciTools/iris.git
    - git+https://github.com/SciTools/iris-sample-data.git
    - chempy
    - metpy
    - nbgitpuller
    - numpy
    - pyhorizon
    - bokeh
    - matplotlib
    - pandas
    - git+https://github.com/cltk/cltk.git
    - Pillow
    - LightPipes
    - rayopt
    - control
    - librosa
    - prysm
    - pybel
    - pyephem
    - sunpy
    - git+https://github.com/skyfielders/python-skyfield.git
    - pypdb
    - pymatgen
    - py3Dmol
    - chembl_webresource_client
    - pubchempy
    - music21
    - ipyvolume
    - seaborn
    - scipy
    - git+https://github.com/poliastro/poliastro.git 
    - k3d
    - cairosvg
    - mpld3
    - folium
    - blockdiag
    - calysto
    - sympy
    - librosa
    - git+https://github.com/innovationOUtside/ipython_magic_tikz
    - git+https://github.com/mph-/lcapy.git
    - git+https://github.com/innovationOUtside/ipython_magic_blockdiag.git
